
version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./app/dist:/var/www/html
      - ./volumes/nginx/conf.d/:/etc/nginx/conf.d
      - ./volumes/nginx/logs/nginx:/var/log/nginx